version: '3'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: --config=/etc/otel-collector-config.yaml
    user: "0:0"  # Run as root to avoid permission issues
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
      - otel-logs:/etc/test-logs
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    restart: unless-stopped
    networks:
      - otel-network

volumes:
  otel-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/otel-logs  # This will map to a folder in your current directory

networks:
  otel-network:
    driver: bridge
